%% MU_RP_FREQUENCY_DIAGNOSTIC
%
% Diagnostica in frequenza della robust performance del controllore
% ottenuto mediante D-K iteration.
%
% Obiettivi:
% 1) visualizzare mu_RP lower/upper bound;
% 2) individuare le bande nelle quali mu_RP > 1;
% 3) individuare la frequenza del massimo;
% 4) confrontare tale zona con i tre canali pesati nominali:
%
%       WS*S
%       WU*K*S
%       WT*T
%
% Le curve dei canali pesati sono utilizzate come supporto al tuning
% dei pesi, NON come decomposizione esatta della structured singular value.

close all;
clc;

%% ========================================================================
% 1. CARICAMENTO
% ========================================================================

load('HINF_setup.mat');
load('ACTUATOR_LUMPED.mat');
load('MU_controller.mat');

I2 = eye(2);

omegaAnalysis = omegaHinf;

fprintf('\n============================================================\n');
fprintf('DIAGNOSTICA IN FREQUENZA DELLA ROBUST PERFORMANCE D-K\n');
fprintf('============================================================\n');

%% ========================================================================
% 2. CLOSED LOOP INCERTO CON K_mu
% ========================================================================

K = K_mu_scaled;

Lunc = ...
    G_uncertain_lumped_scaled*K;

Sunc = ...
    feedback(I2,Lunc);

Tunc = ...
    feedback(Lunc,I2);

Wunc = [
    WS*Sunc
    WU*K*Sunc
    WT*Tunc
];

%% ========================================================================
% 3. LFT DEL SISTEMA INCERTO
% ========================================================================

[Mdelta,Delta,BlockStructure] = ...
    lftdata(Wunc);

%% ========================================================================
% 4. COSTRUZIONE DEL BLOCCO AUGMENTATO PER ROBUST PERFORMANCE
% ========================================================================

nExogenous = ...
    size(Wunc,2);

nPerformance = ...
    size(Wunc,1);

BlockStructureRP = ...
    BlockStructure;

perfBlock = ...
    BlockStructure(1);

perfBlock.Name = ...
    'DeltaPerf';

perfBlock.Size = ...
    [nExogenous nPerformance];

perfBlock.Type = ...
    'ultidyn';

perfBlock.Occurrences = ...
    1;

perfBlock.Simplify = ...
    0;

BlockStructureRP(end+1,1) = ...
    perfBlock;

%% ========================================================================
% 5. MU ROBUST PERFORMANCE IN FREQUENZA
% ========================================================================

fprintf( ...
    'Calcolo mu_RP su %d frequenze...\n', ...
    numel(omegaAnalysis));

tic;

muRP = ...
    mussv( ...
        frd(Mdelta,omegaAnalysis), ...
        BlockStructureRP, ...
        's');

elapsed = toc;

fprintf( ...
    'Calcolo completato in %.2f s.\n', ...
    elapsed);

muRPup = ...
    squeeze( ...
        muRP.ResponseData(1,1,:));

muRPlo = ...
    squeeze( ...
        muRP.ResponseData(1,2,:));

muRPup = muRPup(:);
muRPlo = muRPlo(:);
omegaAnalysis = omegaAnalysis(:);

%% ========================================================================
% 6. PICCO E BANDE CON mu_RP > 1
% ========================================================================

[muPeakUpper,idxPeak] = ...
    max(muRPup);

muPeakLower = ...
    muRPlo(idxPeak);

omegaPeak = ...
    omegaAnalysis(idxPeak);

fprintf('\n============================================================\n');
fprintf('RISULTATO MU_RP\n');
fprintf('============================================================\n');

fprintf( ...
    'Peak upper bound = %.6f\n', ...
    muPeakUpper);

fprintf( ...
    'Lower bound alla frequenza di picco = %.6f\n', ...
    muPeakLower);

fprintf( ...
    'Frequenza di picco = %.6f rad/s\n', ...
    omegaPeak);

maskViolation = ...
    muRPup > 1;

if any(maskViolation)

    d = ...
        diff([ ...
            false; ...
            maskViolation; ...
            false]);

    idxStart = ...
        find(d==1);

    idxEnd = ...
        find(d==-1)-1;

    fprintf('\nBande con upper bound di mu_RP > 1:\n');

    for ib = 1:numel(idxStart)

        fprintf( ...
            '  Banda %d: %.6f - %.6f rad/s\n', ...
            ib, ...
            omegaAnalysis(idxStart(ib)), ...
            omegaAnalysis(idxEnd(ib)));

    end

else

    fprintf('\nNessuna frequenza con upper bound di mu_RP > 1.\n');

end

%% ========================================================================
% 7. CLOSED LOOP NOMINALE
% ========================================================================

Lnom = ...
    G_scaled*K;

Snom = ...
    feedback(I2,Lnom);

Tnom = ...
    feedback(Lnom,I2);

WS_S = ...
    minreal( ...
        WS*Snom, ...
        1e-7);

WU_KS = ...
    minreal( ...
        WU*K*Snom, ...
        1e-7);

WT_T = ...
    minreal( ...
        WT*Tnom, ...
        1e-7);

%% ========================================================================
% 8. MASSIMA SINGULAR VALUE DEI TRE CANALI
% ========================================================================

sigWS = ...
    maxSigmaCurve( ...
        WS_S, ...
        omegaAnalysis);

sigWU = ...
    maxSigmaCurve( ...
        WU_KS, ...
        omegaAnalysis);

sigWT = ...
    maxSigmaCurve( ...
        WT_T, ...
        omegaAnalysis);

%% ========================================================================
% CURVA DELLA NOMINAL PERFORMANCE COMPLESSIVA
% ========================================================================

WnomStack = minreal([ ...
    WS_S
    WU_KS
    WT_T ...
    ],1e-7);

sigNP = ...
    maxSigmaCurve( ...
    WnomStack, ...
    omegaAnalysis);

[gammaNP_exact,omegaPeakNP] = ...
    hinfnorm(WnomStack);

fprintf('\n============================================================\n');
fprintf('NOMINAL PERFORMANCE COMPLESSIVA\n');
fprintf('============================================================\n');

fprintf( ...
    'Gamma nominale esatta = %.6f\n', ...
    gammaNP_exact);

fprintf( ...
    'Frequenza di picco NP = %.6f rad/s\n', ...
    omegaPeakNP);

maskNP = ...
    sigNP > 1;

if any(maskNP)

    dNP = ...
        diff([false; maskNP; false]);

    idxStartNP = ...
        find(dNP==1);

    idxEndNP = ...
        find(dNP==-1)-1;

    fprintf('Bande con sigma(Wnom) > 1:\n');

    for ib = 1:numel(idxStartNP)

        fprintf( ...
            '  Banda %d: %.6f - %.6f rad/s\n', ...
            ib, ...
            omegaAnalysis(idxStartNP(ib)), ...
            omegaAnalysis(idxEndNP(ib)));

    end

else

    fprintf('Nominal performance soddisfatta su tutta la griglia.\n');

end

fprintf('\n============================================================\n');
fprintf('CANALI PESATI ALLA FREQUENZA DEL PICCO MU_RP\n');
fprintf('============================================================\n');

fprintf( ...
    'omega_peak = %.6f rad/s\n', ...
    omegaPeak);

fprintf( ...
    'sigma_max(WS*S)  = %.6f\n', ...
    sigWS(idxPeak));

fprintf( ...
    'sigma_max(WU*KS) = %.6f\n', ...
    sigWU(idxPeak));

fprintf( ...
    'sigma_max(WT*T)  = %.6f\n', ...
    sigWT(idxPeak));

%% ========================================================================
% 9. FIGURA DIAGNOSTICA
% ========================================================================

figure( ...
    'Name','D-K robust performance frequency diagnostic', ...
    'Color','w', ...
    'Position',[100 100 1000 760]);

tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ------------------------------------------------------------------------
% Upper/lower mu_RP
% -------------------------------------------------------------------------

nexttile;

semilogx( ...
    omegaAnalysis, ...
    muRPup, ...
    'LineWidth',1.8);

hold on;

semilogx( ...
    omegaAnalysis, ...
    muRPlo, ...
    '--', ...
    'LineWidth',1.5);

yline( ...
    1, ...
    'k--', ...
    'LineWidth',1.2);

plot( ...
    omegaPeak, ...
    muPeakUpper, ...
    'o', ...
    'MarkerSize',7, ...
    'LineWidth',1.5);

grid on;

xlabel( ...
    '$\omega$ [rad/s]', ...
    'Interpreter','latex');

ylabel( ...
    '$\mu_{RP}$', ...
    'Interpreter','latex');

title( ...
    sprintf( ...
        ['D-K robust performance: ' ...
         '$\\mu_{RP}^{up,max}=%.3f$ a ' ...
         '$\\omega=%.3f$ rad/s'], ...
        muPeakUpper, ...
        omegaPeak), ...
    'Interpreter','latex');

legend( ...
    '$\mu_{RP}^{up}$', ...
    '$\mu_{RP}^{low}$', ...
    'Limite RP = 1', ...
    'Picco', ...
    'Interpreter','latex', ...
    'Location','best');

%% ------------------------------------------------------------------------
% Canali nominali pesati
% -------------------------------------------------------------------------

nexttile;

semilogx( ...
    omegaAnalysis, ...
    sigWS, ...
    'LineWidth',1.6);

hold on;

semilogx( ...
    omegaAnalysis, ...
    sigWU, ...
    'LineWidth',1.6);

semilogx( ...
    omegaAnalysis, ...
    sigWT, ...
    'LineWidth',1.6);

semilogx( ...
    omegaAnalysis, ...
    sigNP, ...
    'k', ...
    'LineWidth',2.0);

xline( ...
    omegaPeakNP, ...
    '--', ...
    'LineWidth',1.2);

yline( ...
    1, ...
    'k--', ...
    'LineWidth',1.2);

xline( ...
    omegaPeak, ...
    'k:', ...
    'LineWidth',1.2);

grid on;

xlabel( ...
    '$\omega$ [rad/s]', ...
    'Interpreter','latex');

ylabel( ...
    'Massima singolar value');

title( ...
    'Canali pesati nominali - supporto al tuning dei pesi');

legend( ...
    '$\bar{\sigma}(W_SS)$', ...
    '$\bar{\sigma}(W_UKS)$', ...
    '$\bar{\sigma}(W_TT)$', ...
    '$\bar{\sigma}([W_SS;W_UKS;W_TT])$', ...
    'Limite = 1', ...
    '$\omega_{\mu,peak}$', ...
    '$\omega_{NP,peak}$', ...
    'Interpreter','latex', ...
    'Location','best');

%% ========================================================================
% 10. SALVATAGGIO
% ========================================================================

resultDir = ...
    fullfile( ...
        pwd, ...
        'result_plot');

if ~exist(resultDir,'dir')
    mkdir(resultDir);
end

outputFile = ...
    fullfile( ...
        resultDir, ...
        'MU_RP_frequency_diagnostic.png');

try

    exportgraphics( ...
        gcf, ...
        outputFile, ...
        'Resolution',300);

catch

    print( ...
        gcf, ...
        outputFile, ...
        '-dpng', ...
        '-r300');

end

fprintf('\nFigura salvata in:\n%s\n', ...
    outputFile);

%% ========================================================================
% FUNZIONE LOCALE
% ========================================================================

function smax = maxSigmaCurve(sys,w)

    H = ...
        freqresp( ...
            sys, ...
            w);

    nFreq = ...
        numel(w);

    smax = ...
        zeros(nFreq,1);

    for i = 1:nFreq

        Hj = ...
            H(:,:,i);

        s = ...
            svd(Hj);

        smax(i) = ...
            s(1);

    end

end