%% PIDCOMP_DECOUPLER_SENSITIVITY_NL
% Sensibilita' del disaccoppiatore statico del controllore hinfstruct
% rispetto alle incertezze parametriche del modello NON LINEARE.
%
% Controller usato in Simulink:
%   HINF_controller_id = 3
%   PID alpha/beta + lead/lag Falpha/Fbeta + Ddec_phys.
%
% Il controllore resta SEMPRE quello sintetizzato sul nominale.
% Si variano soltanto i parametri del plant non lineare tramite delta_plant.
% Per isolare il Ddec si usano: trim coerente col campione, attuatori
% nominali, nessun rumore, nessun disturbo aerodinamico.

close all; clc;

%% 0) Inizializzazione progetto
projectRoot = fileparts(mfilename('fullpath'));
if isempty(projectRoot), projectRoot = pwd; end
cd(projectRoot); addpath(projectRoot);

% Contiene clearvars: eseguirlo prima di definire la campagna.
build_uncertain_linear_model;
projectRoot = pwd; addpath(projectRoot);
init;

load('LQG_2DOF_Controllers.mat');
load('HINF_setup.mat');
load('HINF_controllers.mat');
load('MU_controller.mat');
load('H2_controller.mat');

% Il modello compila anche il ramo LQG.
if ~exist('Aobs','var') || ~exist('Bobs','var') || ...
        ~exist('Cobs','var') || ~exist('Dobs','var') || ~exist('xhat0','var')

    Aobs  = A - Ke*Cmeas;
    Bobs  = [B Ke];
    Cobs  = eye(size(A));
    Dobs  = zeros(size(A,1),size(B,2)+size(Cmeas,1));
    xhat0 = zeros(size(A,1),1);
end

assert(exist('Ddec_scaled','var')==1,'Ddec_scaled mancante.');
assert(exist('P_uncertain_ext','var')==1,'P_uncertain_ext mancante.');

%% 1) Configurazione
cfg.model = 'helicopter_2DOF';

if ~isfile([cfg.model '.slx']) && isfile('helicopter_2DOF(2).slx')
    cfg.model = 'helicopter_2DOF(2)';
end

cfg.nSamples = 15;             % 15 plant incerti + 1 nominale di confronto
cfg.seed = 260902;
cfg.stopTime = 15;

cfg.alphaStepTime = 2;
cfg.betaStepTime  = 8;

cfg.alphaStep = deg2rad(3);
cfg.betaStep  = deg2rad(-5);

cfg.preYawBaseline = 0.75;

% TRUE = consigliato per la figura principale:
% ogni plant parte dal proprio equilibrio.
cfg.useMatchedTrim = true;

cfg.showFigures = false;
cfg.pngResolution = 300;

cfg.outputDir = fullfile( ...
    projectRoot, ...
    'decoupler_sensitivity_result', ...
    'decoupler_sensitivity_PIDcomp');

if ~exist(cfg.outputDir,'dir')
    mkdir(cfg.outputDir);
end

old = [ ...
    dir(fullfile(cfg.outputDir,'*.png')); ...
    dir(fullfile(cfg.outputDir,'*.csv')); ...
    dir(fullfile(cfg.outputDir,'*.mat')) ...
    ];

for k = 1:numel(old)
    delete(fullfile(old(k).folder,old(k).name));
end

load_system(cfg.model);
closeScopes(cfg.model);

%% 2) Test sequenziale per le due direzioni di coupling
%
% 2...8 s:
% alpha cambia, beta_ref resta costante.
% beta-beta_ref = coupling pitch -> yaw.
%
% da 8 s:
% beta cambia, alpha_ref resta costante.
% nuova escursione di e_alpha = coupling yaw -> pitch.

refRun = ref;

refRun.alpha.initial = alpha0;
refRun.alpha.final   = alpha0 + cfg.alphaStep;
refRun.alpha.time    = cfg.alphaStepTime;

refRun.beta.initial = beta0;
refRun.beta.final   = beta0 + cfg.betaStep;
refRun.beta.time    = cfg.betaStepTime;

% Nessun disturbo aerodinamico.
aeroRun = aero;
aeroRun.enable = 0;
aeroRun.alpha.amplitude = 0;
aeroRun.beta.amplitude  = 0;

% Attuatori nominali e rumori disattivati.
actRun = act;
actRun.noiseEnable = 0;

sensorRun = sensor;
sensorRun.noiseEnable = 0;

%% 3) Campioni parametrici del plant non lineare
%
% Ordine:
% [J_alpha, J_y, J_z, m, l, epsilon_p, epsilon_y]

rng(cfg.seed,'twister');

deltaSamples = -1 + 2*rand(7,cfg.nSamples);

% Sample severo gia' usato nel progetto.
deltaRobustTest = [
    +1;
    -1;
    +1;
    +1;
    -1;
    +1;
    -1
    ];

deltaSamples(:,1) = deltaRobustTest;

% Caso 0 nominale + sample 1...15 incerti.
deltaAll = [
    zeros(7,1), ...
    deltaSamples
    ];

nCases = size(deltaAll,2);

%% 4) Preallocazione

outputs = cell(nCases,1);
success = false(nCases,1);

pitchToYawPeakDeg = nan(nCases,1);
yawToPitchPeakDeg = nan(nCases,1);

pitchToYawPeakPct = nan(nCases,1);
yawToPitchPeakPct = nan(nCases,1);

staticPitchToYawPct = nan(nCases,1);
staticYawToPitchPct = nan(nCases,1);

maxAbsU1Cmd = nan(nCases,1);
maxAbsU2Cmd = nan(nCases,1);

saturationHit = false(nCases,1);

u0F1 = nan(nCases,1);
u0F2 = nan(nCases,1);

%% 5) Simulazioni

fprintf('\n============================================================\n');
fprintf('SENSIBILITA'' Ddec - PID+comp SU PLANT NON LINEARE INCERTO\n');
fprintf('15 campioni incerti + nominale\n');
fprintf('============================================================\n');

for k = 1:nCases

    deltaNow = deltaAll(:,k);

    %% Trim
    if cfg.useMatchedTrim

        u0Now = trimAtDelta( ...
            deltaNow,p0,alpha0,beta0);

    else

        u0Now = u0;

    end

    u0F1(k) = u0Now(1);
    u0F2(k) = u0Now(2);

    %% Indicatore statico del Ddec
    [ ...
        staticPitchToYawPct(k), ...
        staticYawToPitchPct(k) ...
        ] = staticMisalignment( ...
            deltaNow, ...
            P_uncertain_ext, ...
            Dy_inv, ...
            Du, ...
            Ddec_scaled);

    %% SimulationInput
    in = Simulink.SimulationInput(cfg.model);

    in = in.setVariable( ...
        'LQG_plant_id',2);

    in = in.setVariable( ...
        'Robust_plant_id',2);

    in = in.setVariable( ...
        'LQG_controller_id',1);

    % 3 = PID + lead/lag + Ddec
    in = in.setVariable( ...
        'HINF_controller_id',3);

    in = in.setVariable( ...
        'ref',refRun);

    in = in.setVariable( ...
        'aero',aeroRun);

    in = in.setVariable( ...
        'delta_plant',deltaNow);

    in = in.setVariable( ...
        'u0',u0Now);

    in = in.setVariable( ...
        'q0',[alpha0;beta0]);

    in = in.setVariable( ...
        'qdot0',[0;0]);

    in = in.setVariable( ...
        'act',actRun);

    in = in.setVariable( ...
        'sensor',sensorRun);

    in = in.setModelParameter( ...
        'StopTime',num2str(cfg.stopTime));

    in = in.setModelParameter( ...
        'UnderSpecifiedDimensionMsg','none');

    if k == 1
        label = 'Nominale';
    else
        label = sprintf('Sample %d',k-1);
    end

    fprintf('[%02d/%02d] %s\n', ...
        k,nCases,label);

    try

        out = sim(in);

        outputs{k} = out;
        success(k) = true;

        logs = getLogs(out);

        a = getTs( ...
            logs,'alpha_Robust');

        b = getTs( ...
            logs,'beta_Robust');

        aRef = getTs( ...
            logs,'alpha_ref');

        bRef = getTs( ...
            logs,'beta_ref');

        u1 = getTs( ...
            logs,'deltaF1_cmd_Robust');

        u2 = getTs( ...
            logs,'deltaF2_cmd_Robust');

        %% Riferimenti sulla griglia delle uscite
        aRefI = interp1( ...
            aRef.Time, ...
            aRef.Data, ...
            a.Time, ...
            'previous', ...
            'extrap');

        bRefI = interp1( ...
            bRef.Time, ...
            bRef.Data, ...
            b.Time, ...
            'previous', ...
            'extrap');

        %% ---------------------------------------------------------------
        % PITCH -> YAW
        % ---------------------------------------------------------------
        pitchWindow = ...
            b.Time >= cfg.alphaStepTime & ...
            b.Time <  cfg.betaStepTime;

        betaCross = ...
            b.Data - bRefI;

        pitchToYawPeakDeg(k) = ...
            rad2deg( ...
                max( ...
                    abs( ...
                        betaCross(pitchWindow))));

        pitchToYawPeakPct(k) = ...
            100 * ...
            pitchToYawPeakDeg(k) / ...
            abs(rad2deg(cfg.alphaStep));

        %% ---------------------------------------------------------------
        % YAW -> PITCH
        % ---------------------------------------------------------------
        eAlpha = ...
            aRefI - a.Data;

        preYaw = ...
            a.Time >= ...
                cfg.betaStepTime-cfg.preYawBaseline & ...
            a.Time < ...
                cfg.betaStepTime-0.05;

        if any(preYaw)

            baseEA = mean( ...
                eAlpha(preYaw));

        else

            baseEA = 0;

        end

        yawWindow = ...
            a.Time >= cfg.betaStepTime;

        alphaCross = ...
            eAlpha - baseEA;

        yawToPitchPeakDeg(k) = ...
            rad2deg( ...
                max( ...
                    abs( ...
                        alphaCross(yawWindow))));

        yawToPitchPeakPct(k) = ...
            100 * ...
            yawToPitchPeakDeg(k) / ...
            abs(rad2deg(cfg.betaStep));

        %% ---------------------------------------------------------------
        % Saturazione
        % ---------------------------------------------------------------
        maxAbsU1Cmd(k) = ...
            max(abs(u1.Data));

        maxAbsU2Cmd(k) = ...
            max(abs(u2.Data));

        saturationHit(k) = ...
            any( ...
                u1.Data < ...
                    actRun.deltaF1_min-1e-9) || ...
            any( ...
                u1.Data > ...
                    actRun.deltaF1_max+1e-9) || ...
            any( ...
                u2.Data < ...
                    actRun.deltaF2_min-1e-9) || ...
            any( ...
                u2.Data > ...
                    actRun.deltaF2_max+1e-9);

    catch ME

        warning( ...
            '%s fallito: %s', ...
            label, ...
            ME.message);

    end
end

%% 6) Tabella risultati

Sample = (0:cfg.nSamples).';

Type = repmat( ...
    "random", ...
    nCases,1);

Type(1) = "nominal";
Type(2) = "stress";

Results = table( ...
    Sample, ...
    Type, ...
    success, ...
    deltaAll(1,:).', ...
    deltaAll(2,:).', ...
    deltaAll(3,:).', ...
    deltaAll(4,:).', ...
    deltaAll(5,:).', ...
    deltaAll(6,:).', ...
    deltaAll(7,:).', ...
    u0F1, ...
    u0F2, ...
    pitchToYawPeakDeg, ...
    pitchToYawPeakPct, ...
    yawToPitchPeakDeg, ...
    yawToPitchPeakPct, ...
    staticPitchToYawPct, ...
    staticYawToPitchPct, ...
    maxAbsU1Cmd, ...
    maxAbsU2Cmd, ...
    saturationHit, ...
    'VariableNames',{ ...
    'Sample', ...
    'Type', ...
    'Success', ...
    'delta_Jalpha', ...
    'delta_Jy', ...
    'delta_Jz', ...
    'delta_m', ...
    'delta_l', ...
    'delta_epsilon_p', ...
    'delta_epsilon_y', ...
    'F1_trim', ...
    'F2_trim', ...
    'PitchToYawPeak_deg', ...
    'PitchToYawPeak_percent', ...
    'YawToPitchPeak_deg', ...
    'YawToPitchPeak_percent', ...
    'StaticPitchToYawMisalignment_percent', ...
    'StaticYawToPitchMisalignment_percent', ...
    'MaxAbsDeltaF1Cmd_N', ...
    'MaxAbsDeltaF2Cmd_N', ...
    'SaturationHit'});

disp(Results);

writetable( ...
    Results, ...
    fullfile( ...
        cfg.outputDir, ...
        'PIDcomp_decoupler_uncertainty_results.csv'));

save( ...
    fullfile( ...
        cfg.outputDir, ...
        'PIDcomp_decoupler_uncertainty_samples.mat'), ...
    'deltaSamples', ...
    'deltaRobustTest', ...
    'cfg', ...
    'Results');

%% 7) Figura 1 - famiglia tracking + cross-coupling

vis = 'off';

if cfg.showFigures
    vis = 'on';
end

f = figure( ...
    'Visible',vis, ...
    'Color','w', ...
    'Position',[80 80 1050 780]);

tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

uncIdx = find(success);
uncIdx(uncIdx==1) = [];

%% Tracking alpha
nexttile;
hold on;
grid on;

for k = uncIdx(:).'

    a = getTs( ...
        getLogs(outputs{k}), ...
        'alpha_Robust');

    plot( ...
        a.Time, ...
        rad2deg(a.Data), ...
        'Color',[.75 .75 .75], ...
        'LineWidth',.8, ...
        'HandleVisibility','off');
end

if success(1)

    logsNom = getLogs(outputs{1});

    a = getTs( ...
        logsNom, ...
        'alpha_Robust');

    ar = getTs( ...
        logsNom, ...
        'alpha_ref');

    plot( ...
        a.Time, ...
        rad2deg(a.Data), ...
        'k', ...
        'LineWidth',2, ...
        'DisplayName','Nominale');

    plot( ...
        ar.Time, ...
        rad2deg(ar.Data), ...
        'k--', ...
        'LineWidth',1.2, ...
        'DisplayName','Riferimento');
end

ylabel( ...
    '$\alpha$ [deg]', ...
    'Interpreter','latex');

title('Pitch tracking');
legend('Location','best');

%% Tracking beta
nexttile;
hold on;
grid on;

for k = uncIdx(:).'

    b = getTs( ...
        getLogs(outputs{k}), ...
        'beta_Robust');

    plot( ...
        b.Time, ...
        rad2deg(b.Data), ...
        'Color',[.75 .75 .75], ...
        'LineWidth',.8, ...
        'HandleVisibility','off');
end

if success(1)

    b = getTs( ...
        logsNom, ...
        'beta_Robust');

    br = getTs( ...
        logsNom, ...
        'beta_ref');

    plot( ...
        b.Time, ...
        rad2deg(b.Data), ...
        'k', ...
        'LineWidth',2, ...
        'DisplayName','Nominale');

    plot( ...
        br.Time, ...
        rad2deg(br.Data), ...
        'k--', ...
        'LineWidth',1.2, ...
        'DisplayName','Riferimento');
end

ylabel( ...
    '$\beta$ [deg]', ...
    'Interpreter','latex');

title('Yaw tracking');
legend('Location','best');

%% Cross pitch -> yaw
nexttile;
hold on;
grid on;

for k = uncIdx(:).'

    logs = getLogs(outputs{k});

    b = getTs( ...
        logs, ...
        'beta_Robust');

    br = getTs( ...
        logs, ...
        'beta_ref');

    brI = interp1( ...
        br.Time, ...
        br.Data, ...
        b.Time, ...
        'previous', ...
        'extrap');

    maskPitchYaw = ...
        b.Time >= cfg.alphaStepTime & ...
        b.Time <  cfg.betaStepTime;

    plot( ...
        b.Time(maskPitchYaw), ...
        rad2deg( ...
            b.Data(maskPitchYaw) - ...
            brI(maskPitchYaw)), ...
        'Color',[.75 .75 .75], ...
        'LineWidth',.8, ...
        'HandleVisibility','off');
end

if success(1)

    b = getTs( ...
        logsNom, ...
        'beta_Robust');

    br = getTs( ...
        logsNom, ...
        'beta_ref');

    brI = interp1( ...
        br.Time, ...
        br.Data, ...
        b.Time, ...
        'previous', ...
        'extrap');

    % Stessa finestra anche per la curva nominale.
    maskPitchYaw = ...
        b.Time >= cfg.alphaStepTime & ...
        b.Time <  cfg.betaStepTime;

    plot( ...
        b.Time(maskPitchYaw), ...
        rad2deg( ...
            b.Data(maskPitchYaw) - ...
            brI(maskPitchYaw)), ...
        'k', ...
        'LineWidth',2, ...
        'DisplayName','Nominale');
end

xlim([ ...
    cfg.alphaStepTime ...
    cfg.betaStepTime]);

yline( ...
    0, ...
    'k--', ...
    'HandleVisibility','off');

xlabel('Time [s]');

ylabel( ...
    '$\beta-\beta_{ref}$ [deg]', ...
    'Interpreter','latex');

title( ...
    'Cross-coupling pitch $\rightarrow$ yaw', ...
    'Interpreter','latex');

legend('Location','best');

%% Cross yaw -> pitch
nexttile;
hold on;
grid on;

for k = uncIdx(:).'

    logs = getLogs(outputs{k});

    a = getTs( ...
        logs, ...
        'alpha_Robust');

    ar = getTs( ...
        logs, ...
        'alpha_ref');

    arI = interp1( ...
        ar.Time, ...
        ar.Data, ...
        a.Time, ...
        'previous', ...
        'extrap');

    eA = arI-a.Data;

    pre = ...
        a.Time >= ...
            cfg.betaStepTime-cfg.preYawBaseline & ...
        a.Time < ...
            cfg.betaStepTime-0.05;

    if any(pre)

        base = mean(eA(pre));

    else

        base = 0;

    end

    plot( ...
        a.Time, ...
        rad2deg(eA-base), ...
        'Color',[.75 .75 .75], ...
        'LineWidth',.8, ...
        'HandleVisibility','off');
end

if success(1)

    a = getTs( ...
        logsNom, ...
        'alpha_Robust');

    ar = getTs( ...
        logsNom, ...
        'alpha_ref');

    arI = interp1( ...
        ar.Time, ...
        ar.Data, ...
        a.Time, ...
        'previous', ...
        'extrap');

    eA = arI-a.Data;

    pre = ...
        a.Time >= ...
            cfg.betaStepTime-cfg.preYawBaseline & ...
        a.Time < ...
            cfg.betaStepTime-0.05;

    if any(pre)

        base = mean(eA(pre));

    else

        base = 0;

    end

    plot( ...
        a.Time, ...
        rad2deg(eA-base), ...
        'k', ...
        'LineWidth',2, ...
        'DisplayName','Nominale');
end

xlim([ ...
    cfg.betaStepTime ...
    cfg.stopTime]);

yline( ...
    0, ...
    'k--', ...
    'HandleVisibility','off');

xlabel('Time [s]');

ylabel( ...
    '$\Delta e_\alpha$ [deg]', ...
    'Interpreter','latex');

title( ...
    'Cross-coupling yaw $\rightarrow$ pitch', ...
    'Interpreter','latex');

legend('Location','best');

sgtitle( ...
    'PID+comp: Ddec nominale fisso su 15 plant non lineari incerti', ...
    'Interpreter','none');

exportFig( ...
    f, ...
    fullfile( ...
        cfg.outputDir, ...
        '01_family_tracking_and_cross_coupling.png'), ...
    cfg);

%% 8) Figura 2 - picchi dinamici

f = figure( ...
    'Visible',vis, ...
    'Color','w', ...
    'Position',[100 100 900 650]);

tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

x = 0:cfg.nSamples;

nexttile;

bar( ...
    x, ...
    pitchToYawPeakPct);

grid on;

ylabel( ...
    'Peak coupling [\%]', ...
    'Interpreter','latex');

title( ...
    '$\max|\beta-\beta_{ref}|/|\Delta\alpha_{ref}|$', ...
    'Interpreter','latex');

nexttile;

bar( ...
    x, ...
    yawToPitchPeakPct);

grid on;

xlabel('Sample (0 = nominale)');

ylabel( ...
    'Peak coupling [\%]', ...
    'Interpreter','latex');

title( ...
    '$\max|\Delta e_\alpha|/|\Delta\beta_{ref}|$', ...
    'Interpreter','latex');

sgtitle( ...
    'Sensibilita'' dinamica del disaccoppiatore', ...
    'Interpreter','none');

exportFig( ...
    f, ...
    fullfile( ...
        cfg.outputDir, ...
        '02_dynamic_cross_coupling_summary.png'), ...
    cfg);

%% 9) Figura 3 - G_delta(0) Ddec_nom

f = figure( ...
    'Visible',vis, ...
    'Color','w', ...
    'Position',[100 100 900 650]);

tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

nexttile;

bar( ...
    x, ...
    staticPitchToYawPct);

grid on;

ylabel( ...
    'Misalignment [\%]', ...
    'Interpreter','latex');

title( ...
    'Virtual pitch: componente lungo yaw');

nexttile;

bar( ...
    x, ...
    staticYawToPitchPct);

grid on;

xlabel('Sample (0 = nominale)');

ylabel( ...
    'Misalignment [\%]', ...
    'Interpreter','latex');

title( ...
    'Virtual yaw: componente lungo pitch');

sgtitle( ...
    '$G_\Delta(0)D_{dec,nom}$: perdita di disaccoppiamento al variare dei parametri', ...
    'Interpreter','latex');

exportFig( ...
    f, ...
    fullfile( ...
        cfg.outputDir, ...
        '03_static_decoupling_misalignment.png'), ...
    cfg);

%% 9b) Figura 4 - sensibilita' parametrica OAT sul modello non lineare
%
% Analisi One-At-a-Time (OAT):
% viene perturbato un solo parametro alla volta, prima al limite inferiore
% (delta_j = -1) e poi al limite superiore (delta_j = +1), mantenendo
% tutti gli altri parametri al valore nominale.
%
% Per ogni parametro vengono quindi eseguite 2 simulazioni:
%
%       7 parametri x 2 estremi = 14 simulazioni
%
% Il controllore rimane SEMPRE quello nominale:
% PID + lead/lag + Ddec ottenuto con hinfstruct.
%
% La sensibilita' associata al parametro j viene definita come:
%
%   S_j = max( |C_j^- - C_0| , |C_j^+ - C_0| )
%
% dove:
%   C_0   = coupling dinamico nominale;
%   C_j^- = coupling con il solo parametro j a delta_j = -1;
%   C_j^+ = coupling con il solo parametro j a delta_j = +1.
%
% L'indice e' espresso in PUNTI PERCENTUALI di coupling.
% Una barra grande indica quindi che la variazione ammessa di quel
% parametro modifica sensibilmente il grado di disaccoppiamento.

fprintf('\n============================================================\n');
fprintf('ANALISI OAT - SENSIBILITA'' PARAMETRICA DEL DISACCOPPIATORE\n');
fprintf('14 simulazioni aggiuntive sul modello non lineare\n');
fprintf('============================================================\n');

% Ordine coerente con delta_plant:
% [J_alpha, J_y, J_z, m, l, epsilon_p, epsilon_y]

paramLabels = { ...
    '$J_\alpha$', ...
    '$J_y$', ...
    '$J_z$', ...
    '$m$', ...
    '$l$', ...
    '$\epsilon_p$', ...
    '$\epsilon_y$'};

nParams = numel(paramLabels);

% Colonna 1 -> delta_j = -1
% Colonna 2 -> delta_j = +1
oatSigns = [-1 +1];

oatPitchToYawPct = nan(nParams,2);
oatYawToPitchPct = nan(nParams,2);

oatSuccess = false(nParams,2);

%% Simulazioni OAT

for j = 1:nParams

    for isign = 1:2

        deltaNow = zeros(7,1);
        deltaNow(j) = oatSigns(isign);

        %% Trim coerente con la realizzazione
        if cfg.useMatchedTrim

            u0Now = trimAtDelta( ...
                deltaNow, ...
                p0, ...
                alpha0, ...
                beta0);

        else

            u0Now = u0;

        end

        %% SimulationInput
        in = Simulink.SimulationInput(cfg.model);

        % Modello non lineare
        in = in.setVariable( ...
            'LQG_plant_id',2);

        in = in.setVariable( ...
            'Robust_plant_id',2);

        % Il ramo LQG deve comunque essere compilabile
        in = in.setVariable( ...
            'LQG_controller_id',1);

        % Controller strutturato:
        % PID + lead/lag + Ddec nominale
        in = in.setVariable( ...
            'HINF_controller_id',3);

        in = in.setVariable( ...
            'ref',refRun);

        in = in.setVariable( ...
            'aero',aeroRun);

        in = in.setVariable( ...
            'delta_plant',deltaNow);

        in = in.setVariable( ...
            'u0',u0Now);

        in = in.setVariable( ...
            'q0',[alpha0;beta0]);

        in = in.setVariable( ...
            'qdot0',[0;0]);

        in = in.setVariable( ...
            'act',actRun);

        in = in.setVariable( ...
            'sensor',sensorRun);

        in = in.setModelParameter( ...
            'StopTime',num2str(cfg.stopTime));

        % Mantiene disabilitato il diagnostico gia' eliminato
        % dalla campagna principale.
        in = in.setModelParameter( ...
            'UnderSpecifiedDimensionMsg','none');

        if oatSigns(isign) < 0
            signLabel = '-1';
        else
            signLabel = '+1';
        end

        fprintf( ...
            '[OAT %02d/%02d] Parametro %d/%d, delta = %s\n', ...
            2*(j-1)+isign, ...
            2*nParams, ...
            j, ...
            nParams, ...
            signLabel);

        try

            outOAT = sim(in);

            logsOAT = getLogs(outOAT);

            a = getTs( ...
                logsOAT, ...
                'alpha_Robust');

            b = getTs( ...
                logsOAT, ...
                'beta_Robust');

            aRef = getTs( ...
                logsOAT, ...
                'alpha_ref');

            bRef = getTs( ...
                logsOAT, ...
                'beta_ref');

            %% Riferimenti sulle griglie temporali
            aRefI = interp1( ...
                aRef.Time, ...
                aRef.Data, ...
                a.Time, ...
                'previous', ...
                'extrap');

            bRefI = interp1( ...
                bRef.Time, ...
                bRef.Data, ...
                b.Time, ...
                'previous', ...
                'extrap');

            %% ===========================================================
            % PITCH -> YAW
            % ============================================================

            pitchWindow = ...
                b.Time >= cfg.alphaStepTime & ...
                b.Time <  cfg.betaStepTime;

            betaCross = ...
                b.Data - bRefI;

            pitchToYawDegOAT = ...
                rad2deg( ...
                    max( ...
                        abs( ...
                            betaCross(pitchWindow))));

            oatPitchToYawPct(j,isign) = ...
                100 * ...
                pitchToYawDegOAT / ...
                abs(rad2deg(cfg.alphaStep));

            %% ===========================================================
            % YAW -> PITCH
            % ============================================================

            eAlpha = ...
                aRefI - a.Data;

            preYaw = ...
                a.Time >= ...
                    cfg.betaStepTime-cfg.preYawBaseline & ...
                a.Time < ...
                    cfg.betaStepTime-0.05;

            if any(preYaw)

                baseEA = ...
                    mean(eAlpha(preYaw));

            else

                baseEA = 0;

            end

            yawWindow = ...
                a.Time >= cfg.betaStepTime;

            alphaCross = ...
                eAlpha - baseEA;

            yawToPitchDegOAT = ...
                rad2deg( ...
                    max( ...
                        abs( ...
                            alphaCross(yawWindow))));

            oatYawToPitchPct(j,isign) = ...
                100 * ...
                yawToPitchDegOAT / ...
                abs(rad2deg(cfg.betaStep));

            oatSuccess(j,isign) = true;

        catch ME

            warning( ...
                'OAT parametro %d, delta=%s fallito: %s', ...
                j, ...
                signLabel, ...
                ME.message);

        end

    end

end

%% Calcolo della sensibilita' parametrica
%
% Il nominale e' gia' stato simulato nella campagna principale:
%
%   pitchToYawPeakPct(1)
%   yawToPitchPeakPct(1)

C0_pitchToYaw = ...
    pitchToYawPeakPct(1);

C0_yawToPitch = ...
    yawToPitchPeakPct(1);

paramSensitivityPitchToYaw = ...
    nan(nParams,1);

paramSensitivityYawToPitch = ...
    nan(nParams,1);

for j = 1:nParams

    deltaCouplingPitchToYaw = ...
        abs( ...
            oatPitchToYawPct(j,:) - ...
            C0_pitchToYaw);

    deltaCouplingYawToPitch = ...
        abs( ...
            oatYawToPitchPct(j,:) - ...
            C0_yawToPitch);

    paramSensitivityPitchToYaw(j) = ...
        max( ...
            deltaCouplingPitchToYaw, ...
            [], ...
            'omitnan');

    paramSensitivityYawToPitch(j) = ...
        max( ...
            deltaCouplingYawToPitch, ...
            [], ...
            'omitnan');

end

%% Figura 4

f = figure( ...
    'Visible',vis, ...
    'Color','w', ...
    'Position',[100 100 950 700]);

tiledlayout( ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

y = 1:nParams;

%% Sensibilita' pitch -> yaw
nexttile;

barh( ...
    y, ...
    paramSensitivityPitchToYaw);

grid on;

set( ...
    gca, ...
    'YTick',y, ...
    'YTickLabel',paramLabels, ...
    'TickLabelInterpreter','latex', ...
    'YDir','reverse');

xlabel( ...
    'Max variazione del coupling [punti percentuali]');

ylabel('Parametro');

title( ...
    sprintf( ...
        ['Pitch $\\rightarrow$ yaw: ' ...
         '$\\max\\{|C_j^- - C_0|,|C_j^+ - C_0|\\}$, ' ...
         '$C_0=%.3f\\%%$'], ...
        C0_pitchToYaw), ...
    'Interpreter','latex');

%% Sensibilita' yaw -> pitch
nexttile;

barh( ...
    y, ...
    paramSensitivityYawToPitch);

grid on;

set( ...
    gca, ...
    'YTick',y, ...
    'YTickLabel',paramLabels, ...
    'TickLabelInterpreter','latex', ...
    'YDir','reverse');

xlabel( ...
    'Max variazione del coupling [punti percentuali]');

ylabel('Parametro');

title( ...
    sprintf( ...
        ['Yaw $\\rightarrow$ pitch: ' ...
         '$\\max\\{|C_j^- - C_0|,|C_j^+ - C_0|\\}$, ' ...
         '$C_0=%.3f\\%%$'], ...
        C0_yawToPitch), ...
    'Interpreter','latex');

sgtitle( ...
    ['Sensibilita'' parametrica OAT del disaccoppiatore ' ...
     'sul modello non lineare'], ...
    'Interpreter','none');

exportFig( ...
    f, ...
    fullfile( ...
        cfg.outputDir, ...
        '04_OAT_parameter_sensitivity.png'), ...
    cfg);

fprintf('\n');
fprintf('Analisi OAT completata.\n');
fprintf('Figura salvata in:\n');
fprintf('  %s\n', ...
    fullfile( ...
        cfg.outputDir, ...
        '04_OAT_parameter_sensitivity.png'));

%% 10) Riepilogo

idx = 2:nCases;
idx = idx(success(idx));

fprintf('\n============================================================\n');
fprintf('RIEPILOGO\n');
fprintf('============================================================\n');

if ~isempty(idx)

    fprintf( ...
        'Pitch -> yaw [%%]: min %.3f | mean %.3f | max %.3f\n', ...
        min(pitchToYawPeakPct(idx)), ...
        mean(pitchToYawPeakPct(idx)), ...
        max(pitchToYawPeakPct(idx)));

    fprintf( ...
        'Yaw -> pitch [%%]: min %.3f | mean %.3f | max %.3f\n', ...
        min(yawToPitchPeakPct(idx)), ...
        mean(yawToPitchPeakPct(idx)), ...
        max(yawToPitchPeakPct(idx)));

end

fprintf( ...
    'Nominale pitch -> yaw: %.3f %%\n', ...
    pitchToYawPeakPct(1));

fprintf( ...
    'Nominale yaw -> pitch: %.3f %%\n', ...
    yawToPitchPeakPct(1));

if any(saturationHit(success))

    warning([ ...
        'Almeno un campione richiede comandi oltre i limiti: ' ...
        'la saturazione puo'' contaminare il test.']);

else

    fprintf( ...
        'Nessun superamento dei limiti di comando rilevato.\n');

end

fprintf( ...
    'Output: %s\n', ...
    cfg.outputDir);

%% ========================================================================
% FUNZIONI LOCALI
% =========================================================================

function u0Now = trimAtDelta( ...
    delta,p0,alpha0,beta0)

    m = ...
        p0.m * ...
        (1+0.10*delta(4));

    ep = ...
        p0.epsilon_p * ...
        (1+0.30*delta(6));

    ey = ...
        p0.epsilon_y * ...
        (1+0.30*delta(7));

    E = [
        cos(beta0),        ep*sin(beta0);
        ey*sin(alpha0),    cos(alpha0)
        ];

    u0Now = ...
        E \ [
        m*p0.g*sin(alpha0);
        0
        ];

end

function [p2y,y2p] = staticMisalignment( ...
    delta,PuncExt,Dy_inv,Du,Ddec)

    P = ...
        evaluatePlant( ...
            PuncExt, ...
            delta);

    G = ...
        P([1 3],[1 2]);

    M = ...
        dcgain( ...
            Dy_inv * ...
            G * ...
            Du) * ...
        Ddec;

    p2y = ...
        100 * ...
        abs(M(2,1)) / ...
        max(norm(M(:,1),2),eps);

    y2p = ...
        100 * ...
        abs(M(1,2)) / ...
        max(norm(M(:,2),2),eps);

end

function Pdet = evaluatePlant( ...
    PuncExt,delta)

    names = {
        'J_alpha'
        'J_y'
        'J_z'
        'm'
        'l'
        'epsilon_p'
        'epsilon_y'
        };

    U = ...
        PuncExt.Uncertainty;

    Pwork = ...
        PuncExt;

    for i = 1:numel(names)

        blk = ...
            U.(names{i});

        d = ...
            max( ...
                -1, ...
                min( ...
                    1, ...
                    delta(i)));

        if d >= 0

            value = ...
                blk.NominalValue + ...
                d * ...
                ( ...
                    blk.Range(2) - ...
                    blk.NominalValue);

        else

            value = ...
                blk.NominalValue + ...
                (-d) * ...
                ( ...
                    blk.Range(1) - ...
                    blk.NominalValue);

        end

        Pwork = ...
            usubs( ...
                Pwork, ...
                names{i}, ...
                value);

    end

    Pdet = ...
        ss(Pwork);

end

function logs = getLogs(out)

    try

        logs = out.logsout;

    catch

        logs = out.get('logsout');

    end

    if isempty(logs)
        error('logsout non disponibile.');
    end

end

function ts = getTs(logs,name)

    el = ...
        logs.get(name);

    if isempty(el)

        error( ...
            'Segnale %s non trovato in logsout.', ...
            name);

    end

    ts = ...
        el.Values;

    ts.Data = ...
        squeeze(ts.Data);

end

function exportFig( ...
    f,path,cfg)

    try

        exportgraphics( ...
            f, ...
            path, ...
            'Resolution', ...
            cfg.pngResolution);

    catch

        print( ...
            f, ...
            path, ...
            '-dpng', ...
            sprintf( ...
                '-r%d', ...
                cfg.pngResolution));

    end

    close(f);

end

function closeScopes(model)

    scopes = ...
        find_system( ...
            model, ...
            'LookUnderMasks','all', ...
            'FollowLinks','on', ...
            'MatchFilter', ...
                @Simulink.match.allVariants, ...
            'BlockType','Scope');

    for i = 1:numel(scopes)

        try

            set_param( ...
                scopes{i}, ...
                'Open', ...
                'off');

        catch
        end

    end

end